### ISSUE TITLE
Can i run this on a CPU ?

### ISSUE THREAD

**Issue by pidugusundeep** [martiansideofthemoon/squash-generation#10]
Is there any parameter in ```_check_driver``` method I could skip and do the training on my local CPU  with 4 cores and 19G of ram?

**Comment by martiansideofthemoon** [comment]
Yes you can run inference, I've run it on 4 CPUs and 8 GB RAM as well.

**Comment by aantix** [comment]
How long did inference take with 4 CPUs and 8GB of ram?

**Comment by martiansideofthemoon** [comment]
8 GB might be cutting it close, but for a single paragraph i'd say about 1-1.5 minutes
