### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by pidugusundeep** [martiansideofthemoon/squash-generation#11]
https://github.com/martiansideofthemoon/squash-generation/blob/c7fa64f09c4eef8bb2db58aa07fa28a7ead40f9c/data/question-classifier/analysis.py#L76

**Comment by martiansideofthemoon** [comment]
Apologies, I've not cleaned up `squash-generation/data/question-classifier` properly. This is probably going to be the `data/specificity_qa_dataset/dev.pickle`.  Feel free to send a PR.
