### ISSUE TITLE
Using squash-generation for QG?

### ISSUE THREAD

**Issue by nleclercq** [martiansideofthemoon/squash-generation#13]
Hi, 
I'm looking for a question generation (QG) solution to generate a SQuAD like dataset. Would it be a good to try to use squash-generation as a pure QG tool? In case it makes sense, what is the best way to generate questions from arbitrary text using squash-generation? 
Thanks for your feedback.

**Comment by martiansideofthemoon** [comment]
yes, you can use `squash-generation/question-generation` independently.

**Comment by nleclercq** [comment]
Thanks. How should I format the input to generate my own questions?
