### ISSUE TITLE
Input format to generate custom questions?

### ISSUE THREAD

**Issue by nleclercq** [martiansideofthemoon/squash-generation#15]
Hi,
How should we format the input to generate our own questions?
I mean, how can we inject an arbitrary text into the pre-trained question generation model (i.e. question-generation/gpt2_corefs_question_generation)?
Thanks

**Comment by martiansideofthemoon** [comment]
I recommend using `squash/pipeline-custom.sh` without the question answering and filtering modules. For more details look at https://github.com/martiansideofthemoon/squash-generation#squashing
