### ISSUE TITLE
Comment on top_p, gen_frac and spec_frac values in metadata.json

### ISSUE THREAD

**Issue by nleclercq** [martiansideofthemoon/squash-generation#16]
Could you please tell us a few words about the **top_p**, **gen_frac** and **spec_frac** settings located in **metadata.json**? Where do these values come from? How to set them properly?
Thanks.

**Comment by martiansideofthemoon** [comment]
`top_p` is the `p` value in nucleus sampling. As the p-value increases, the likelihood of sampling from the tail distribution of the softmax increases. Refer to [Holtzman et al. 2019](https://arxiv.org/pdf/1904.09751.pdf) for more details.

`gen_frac` and `spec_frac` are used during the filtering of the SQUASH documents. You don't need to worry about them for just performing question generation.

Nevertheless, increasing `gen_frac` will retain a larger number of general, high-level overview questions about the input text, which form the upper layer of the QA hierarchy.

Similarly, increasing `spec_frac` will retain a larger number of specific, low-level drill-down questions about the input text, which form the lower layer of the QA hierarchy

**Comment by martiansideofthemoon** [comment]
The default values should give you good looking questions.
