### ISSUE TITLE
'answer_start' are wrong

### ISSUE THREAD

**Issue by nleclercq** [martiansideofthemoon/squash-generation#22]
While trying to fine-tune a BERT model with some questions generated by SQUASH, I noticed that the 'answer_start' offset in the 'context' is often wrong (at least on the few questions I've checked). The offset error is not constant. 

EDIT: please, let me double check something in my code before trying to answer. sorry.

**Comment by martiansideofthemoon** [comment]
Feel free to re-open if you find an issue
