### ISSUE TITLE
How to inject generated questions into the pre-trained BERT model manually?

### ISSUE THREAD

**Issue by nleclercq** [martiansideofthemoon/squash-generation#24]
How to inject generated questions into the pre-trained BERT model manually?
I mean, "without using Slurm". In fact I have plenty of questions generated by the QG layer and I'd to obtain the "predicted" version of the answers.
Thanks.

**Comment by martiansideofthemoon** [comment]
i'm not sure what you mean by "manually". Slurm is not compulsory, the scripts work without slurm too.
