### ISSUE TITLE
Unable to run pipeline_custom.sh

### ISSUE THREAD

**Issue by kwangje** [martiansideofthemoon/squash-generation#25]
There is no problem of executing ```squash/pipeline.sh```
Please let me know how I can use ```squash/pipeline_custom.sh quac_869``` without errors.

I created ```squash/temp/quac_869``` and ```squash/temp/quac_869/metadata.json``` just as you said. When I tried to execute ```squash/pipeline_custom.sh quac_869```, it automatically creates "input.pkl" file, so I think there is no problem of generating questions ..

However, it cannot move on to the next step of QA. 
	--predict_file squash/temp/generated_questions.json \
	--output_dir squash/temp \
It continuously cannot find the files such as generated_questions.json, ... (Sorry. My computer is down and I forgot the exact name of files ...)

Please help me

**Comment by martiansideofthemoon** [comment]
The issue with the `pipeline_custom.sh` script. I've used `squash/temp` in a number of places instead of `squash/temp/$KEY`. Would you like to fix it?

**Comment by kwangje** [comment]
I just add the path /%key/ behind the /temp/,
and add the argument --key $key

Now it is working ! Thank you so much for your wonderful project 

```
KEY=$1

echo $KEY

echo 'Extracting answers ...'
python squash/extract_answers.py --key $KEY

echo 'Generating questions ...'
python question-generation/interact.py \
	--model_checkpoint question-generation/gpt2_corefs_question_generation \
	--filename squash/temp/$KEY/input.pkl \
	--model_type gpt2 \
	--key $KEY

echo 'Running QA module ...'
python question-answering/run_squad.py \
	--bert_model question-answering/bert_large_qa_model \
	--do_predict \
	--do_lower_case \
	--predict_file squash/temp/$KEY/generated_questions.json \
	--output_dir squash/temp/$KEY \
	--version_2_with_negative

echo 'Combining Q and A ...'
python squash/combine_qa.py --key $KEY

echo 'Filtering bad Q/As ...'
python squash/filter.py --key $KEY

```

**Comment by martiansideofthemoon** [comment]
Could you leave a PR?
