### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'set_num_special_tokens'

### ISSUE THREAD

**Issue by aravindchaluvadi** [martiansideofthemoon/squash-generation#31]
I am facing the below issue while running the Question Generation module bash file for gpt-model

$ bash schedule_gpt.sh

**Error Track Trace:**

$ bash schedule_gpt.sh
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
WARNING:question-generation/train.py:Running process 0
INFO:question-generation/train.py:Arguments: Namespace(dataset_cache='data/temp_dataset/cache', dataset_path='data/temp_dataset/instances', device='cuda', eval_before_start=False, fp16='', gradient_accumulation_steps=8, local_rank=0, lr=6.25e-05, max_norm=1.0, model_checkpoint='openai-gpt', n_epochs=4, output_dir='question-generation/gpt_question_generation', train_batch_size=4, valid_batch_size=4)
INFO:question-generation/train.py:Prepare tokenizer, pretrained model and optimizer - add special tokens for fine-tuning
WARNING:question-generation/train.py:Running process 2
WARNING:question-generation/train.py:Running process 3
WARNING:question-generation/train.py:Running process 1
INFO:pytorch_pretrained_bert.tokenization_openai:loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-vocab.json from cache at /home/xxxx/.pytorch_pretrained_bert/4ab93d0cd78ae80e746c27c9cd34e90b470abdabe0590c9ec742df61625ba310.b9628f6fe5519626534b82ce7ec72b22ce0ae79550325f45c604a25c0ad87fd6
INFO:pytorch_pretrained_bert.tokenization_openai:loading merges file https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-merges.txt from cache at /home/xxxx/.pytorch_pretrained_bert/0f8de0dbd6a2bb6bde7d758f4c120dd6dd20b46f2bf0a47bc899c89f46532fde.20808570f9a3169212a577f819c845330da870aeb14c40f7319819fce10c3b76
INFO:pytorch_pretrained_bert.file_utils:https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-pytorch_model.bin not found in cache, downloading to /tmp/tmpzxmm547b
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 478750579/478750579 [11:10<00:00, 713727.32B/s]
 99%|██████████████████████████████████████████████████████████████████████████████████████████████▋ | 472000512/478750579 [11:10<00:10, 632695.17B/s]ERROR:pytorch_pretrained_bert.modeling_openai:Model name 'openai-gpt' was not found in model name list (openai-gpt). We assumed 'openai-gpt' was a path or url but couldn't find files https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-pytorch_model.bin and https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-config.json at this path or url.
Traceback (most recent call last):
  File "question-generation/train.py", line 375, in <module>
    train()
  File "question-generation/train.py", line 270, in train
    model.set_num_special_tokens(len(SPECIAL_TOKENS))
AttributeError: 'NoneType' object has no attribute 'set_num_special_tokens'
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 478750579/478750579 [11:16<00:00, 707432.58B/s]
 98%|██████████████████████████████████████████████████████████████████████████████████████████████▏ | 469928960/478750579 [11:16<00:25, 351072.52B/s]ERROR:pytorch_pretrained_bert.modeling_openai:Model name 'openai-gpt' was not found in model name list (openai-gpt). We assumed 'openai-gpt' was a path or url but couldn't find files https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-pytorch_model.bin and https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-config.json at this path or url.
Traceback (most recent call last):
  File "question-generation/train.py", line 375, in <module>
    train()
  File "question-generation/train.py", line 270, in train
    model.set_num_special_tokens(len(SPECIAL_TOKENS))
AttributeError: 'NoneType' object has no attribute 'set_num_special_tokens'
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 478750579/478750579 [11:21<00:00, 702068.16B/s]
INFO:pytorch_pretrained_bert.file_utils:copying /tmp/tmpzxmm547b to cache at /home/xxxx/.pytorch_pretrained_bert/e45ee1afb14c5d77c946e66cb0fa70073a77882097a1a2cefd51fd24b172355e.e7ee3fcd07c695a4c9f31ca735502c090230d988de03202f7af9ebe1c3a4054c
ERROR:pytorch_pretrained_bert.modeling_openai:Model name 'openai-gpt' was not found in model name list (openai-gpt). We assumed 'openai-gpt' was a path or url but couldn't find files https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-pytorch_model.bin and https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-config.json at this path or url.
INFO:pytorch_pretrained_bert.tokenization_openai:Special tokens {'<bos>': 40478, '<eos>': 40479, '<paragraph>': 40480, '<answer-general>': 40481, '<answer-specific>': 40482, '<question-general>': 40483, '<question-specific>': 40484, '<pad>': 40485}
Traceback (most recent call last):
  File "question-generation/train.py", line 375, in <module>
    train()
  File "question-generation/train.py", line 270, in train
    model.set_num_special_tokens(len(SPECIAL_TOKENS))
AttributeError: 'NoneType' object has no attribute 'set_num_special_tokens'
 99%|██████████████████████████████████████████████████████████████████████████████████████████████▋ | 472035328/478750579 [11:21<00:12, 531161.49B/s]Traceback (most recent call last):
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/xxxx/anaconda3/envs/squash/bin/python3', '-u', 'question-generation/train.py', '--local_rank=3', '--n_epochs', '4', '--output_dir', 'question-generation/gpt_question_generation']' returned non-zero exit status 1.
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 478750579/478750579 [11:27<00:00, 696058.16B/s]
ERROR:pytorch_pretrained_bert.modeling_openai:Model name 'openai-gpt' was not found in model name list (openai-gpt). We assumed 'openai-gpt' was a path or url but couldn't find files https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-pytorch_model.bin and https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-config.json at this path or url.
Traceback (most recent call last):
  File "question-generation/train.py", line 375, in <module>
    train()
  File "question-generation/train.py", line 270, in train
    model.set_num_special_tokens(len(SPECIAL_TOKENS))
AttributeError: 'NoneType' object has no attribute 'set_num_special_tokens'

**Comment by martiansideofthemoon** [comment]
You are probably not using 4 GPUs. You can reduce the number of GPUs (processes) in the bash script

**Comment by aravindchaluvadi** [comment]
I am still facing the same error 
i have one gpu i.e. 
1660ti with 6GB memory and
4GB ram with 6 core processor

**Below is my bash file of "schedule_gpt.sh"**

#!/bin/sh
#SBATCH --job-name=job_squash_gpt
#SBATCH -o /media/tg003/NewVolume/squash-generation/logs/log_squash_gpt_new_dir.txt
#SBATCH --time=167:00:00
#SBATCH --partition=1660ti-long
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=6
#SBATCH --mem=10GB
#SBATCH -d singleton

cd /media/tg003/NewVolume/squash-generation

python3 -m torch.distributed.launch --nproc_per_node=1 question-generation/train.py --n_epochs 1 --output_dir question-generation/gpt_question_generation


**and Below is the error stack Trace:**

$ bash schedule_gpt.sh
WARNING:question-generation/train.py:Running process 0
INFO:question-generation/train.py:Arguments: Namespace(dataset_cache='data/temp_dataset/cache', dataset_path='data/temp_dataset/instances', device='cuda', eval_before_start=False, fp16='', gradient_accumulation_steps=8, local_rank=0, lr=6.25e-05, max_norm=1.0, model_checkpoint='openai-gpt', n_epochs=1, output_dir='question-generation/gpt_question_generation', train_batch_size=4, valid_batch_size=4)
INFO:question-generation/train.py:Prepare tokenizer, pretrained model and optimizer - add special tokens for fine-tuning
INFO:pytorch_pretrained_bert.tokenization_openai:loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-vocab.json from cache at /home/tg003/.pytorch_pretrained_bert/4ab93d0cd78ae80e746c27c9cd34e90b470abdabe0590c9ec742df61625ba310.b9628f6fe5519626534b82ce7ec72b22ce0ae79550325f45c604a25c0ad87fd6
INFO:pytorch_pretrained_bert.tokenization_openai:loading merges file https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-merges.txt from cache at /home/tg003/.pytorch_pretrained_bert/0f8de0dbd6a2bb6bde7d758f4c120dd6dd20b46f2bf0a47bc899c89f46532fde.20808570f9a3169212a577f819c845330da870aeb14c40f7319819fce10c3b76
INFO:pytorch_pretrained_bert.file_utils:https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-pytorch_model.bin not found in cache, downloading to /tmp/tmpqq9vn1n7
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 478750579/478750579 [04:17<00:00, 1858558.63B/s]
INFO:pytorch_pretrained_bert.file_utils:copying /tmp/tmpqq9vn1n7 to cache at /home/tg003/.pytorch_pretrained_bert/e45ee1afb14c5d77c946e66cb0fa70073a77882097a1a2cefd51fd24b172355e.e7ee3fcd07c695a4c9f31ca735502c090230d988de03202f7af9ebe1c3a4054c
ERROR:pytorch_pretrained_bert.modeling_openai:Model name 'openai-gpt' was not found in model name list (openai-gpt). We assumed 'openai-gpt' was a path or url but couldn't find files https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-pytorch_model.bin and https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-config.json at this path or url.
INFO:pytorch_pretrained_bert.tokenization_openai:Special tokens {'<bos>': 40478, '<eos>': 40479, '<paragraph>': 40480, '<answer-general>': 40481, '<answer-specific>': 40482, '<question-general>': 40483, '<question-specific>': 40484, '<pad>': 40485}
Traceback (most recent call last):
  File "question-generation/train.py", line 375, in <module>
    train()
  File "question-generation/train.py", line 270, in train
    model.set_num_special_tokens(len(SPECIAL_TOKENS))
AttributeError: 'NoneType' object has no attribute 'set_num_special_tokens'
Traceback (most recent call last):
  File "/home/tg003/anaconda3/envs/squash/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/tg003/anaconda3/envs/squash/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tg003/anaconda3/envs/squash/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/tg003/anaconda3/envs/squash/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/tg003/anaconda3/envs/squash/bin/python3', '-u', 'question-generation/train.py', '--local_rank=0', '--n_epochs', '1', '--output_dir', 'question-generation/gpt_question_generation']' returned non-zero exit status 1.

**Comment by martiansideofthemoon** [comment]
Seems like there is some incompatibility with the `pytorch-pretrained-bert` library. What's present in your cache?

`ls -l  /home/tg003/.pytorch_pretrained_bert/e45ee1afb14c5d77c946e66cb0fa70073a77882097a1a2cefd51fd24b172355e.e7ee3fcd07c695a4c9f31ca735502c090230d988de03202f7af9ebe1c3a4054c`

**Comment by martiansideofthemoon** [comment]
My best guess is that you have either less space in that directory or some permission issue. The actual error is happening here - https://github.com/martiansideofthemoon/squash-generation/blob/master/pytorch-pretrained-BERT/pytorch_pretrained_bert/file_utils.py#L237-L239

**Comment by aravindchaluvadi** [comment]
When i the above command  I am getting No such file or directory error hence when i change the command to the below one , these where the results:


`$ ls -l  /home/xxxx/.pytorch_pretrained_bert/`
total 1256
-rw-r--r-- 1 root root 458495 Jan  3 12:57 0f8de0dbd6a2bb6bde7d758f4c120dd6dd20b46f2bf0a47bc899c89f46532fde.20808570f9a3169212a577f819c845330da870aeb14c40f7319819fce10c3b76
-rw-r--r-- 1 root root    132 Jan  3 12:57 0f8de0dbd6a2bb6bde7d758f4c120dd6dd20b46f2bf0a47bc899c89f46532fde.20808570f9a3169212a577f819c845330da870aeb14c40f7319819fce10c3b76.json
-rw-r--r-- 1 root root 815973 Jan  3 12:57 4ab93d0cd78ae80e746c27c9cd34e90b470abdabe0590c9ec742df61625ba310.b9628f6fe5519626534b82ce7ec72b22ce0ae79550325f45c604a25c0ad87fd6
-rw-r--r-- 1 root root    132 Jan  3 12:57 4ab93d0cd78ae80e746c27c9cd34e90b470abdabe0590c9ec742df61625ba310.b9628f6fe5519626534b82ce7ec72b22ce0ae79550325f45c604a25c0ad87fd6.json

**Comment by martiansideofthemoon** [comment]
i believe this error is due to disk space. Please run `export PYTORCH_PRETRAINED_BERT_CACHE=<some-big-directory>` before running the command.

**Comment by aravindchaluvadi** [comment]
Yes That Worked Thanks 
but I am facing an new issue: 


INFO:pytorch_pretrained_bert.modeling_openai:loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-config.json from cache at /media/xxxx/NewVolume/pre/a27bb7c70e9002d7558d2682d5a95f3c0a8b31034616309459e0b51ef07ade09.f59b19eb0e361a0230a1106b66b8c6e7a994cb200cd63d9190cda8d56d75ff85
INFO:pytorch_pretrained_bert.modeling_openai:Model config {
  "afn": "gelu",
  "attn_pdrop": 0.1,
  "embd_pdrop": 0.1,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "n_ctx": 512,
  "n_embd": 768,
  "n_head": 12,
  "n_layer": 12,
  "n_positions": 512,
  "n_special": 0,
  "predict_special_tokens": true,
  "resid_pdrop": 0.1,
  "vocab_size": 40478
}

INFO:pytorch_pretrained_bert.tokenization_openai:Special tokens {'<bos>': 40478, '<eos>': 40479, '<paragraph>': 40480, '<answer-general>': 40481, '<answer-specific>': 40482, '<question-general>': 40483, '<question-specific>': 40484, '<pad>': 40485}
WARNING:pytorch_pretrained_bert.optimization:t_total value of -1 results in schedule not being applied
Traceback (most recent call last):
  File "question-generation/train.py", line 375, in <module>
    train()
  File "question-generation/train.py", line 279, in train
    model = DistributedDataParallel(model, device_ids=[args.local_rank], output_device=args.local_rank)
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 268, in __init__
    self.process_group = _get_default_group()
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 267, in _get_default_group
    raise RuntimeError("Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
Traceback (most recent call last):
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/xxxx/anaconda3/envs/squash/bin/python3', '-u', 'question-generation/train.py', '--local_rank=0', '--n_epochs', '1', '--output_dir', 'question-generation/gpt_question_generation']' returned non-zero exit status 1.

**Comment by martiansideofthemoon** [comment]
Weird, it's something to do with distributed training. What's your bash script? Does increasing `--nproc_per_node=1` help? Have you set `CUDA_VISIBLE_DEVICES=0`?

**Comment by aravindchaluvadi** [comment]
**Below is the my bash file**

#!/bin/sh
#SBATCH --job-name=job_squash_gpt
#SBATCH -o /media/xxxx/NewVolume/squash-generation/logs/log_squash_gpt_new_dir.txt
#SBATCH --time=167:00:00
#SBATCH --partition=1660ti-long
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=6
#SBATCH --mem=10GB
#SBATCH -d singleton

cd /media/xxxx/NewVolume/squash-generation

python3 -m torch.distributed.launch --nproc_per_node=1 question-generation/train.py --n_epochs 1 --output_dir question-generation/gpt_question_generation


Yes i have set CUDA_VISIBLE_DEVICES=0 using Export command in Ubuntu but still I am facing the below issue:


```
$ bash schedule_gpt.sh
WARNING:question-generation/train.py:Running process 0
INFO:question-generation/train.py:Arguments: Namespace(dataset_cache='data/temp_dataset/cache', dataset_path='data/temp_dataset/instances', device='cuda', eval_before_start=False, fp16='', gradient_accumulation_steps=8, local_rank=0, lr=6.25e-05, max_norm=1.0, model_checkpoint='openai-gpt', n_epochs=1, output_dir='question-generation/gpt_question_generation', train_batch_size=4, valid_batch_size=4)
INFO:question-generation/train.py:Prepare tokenizer, pretrained model and optimizer - add special tokens for fine-tuning
INFO:pytorch_pretrained_bert.tokenization_openai:loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-vocab.json from cache at /media/xxxx/NewVolume/pre/4ab93d0cd78ae80e746c27c9cd34e90b470abdabe0590c9ec742df61625ba310.b9628f6fe5519626534b82ce7ec72b22ce0ae79550325f45c604a25c0ad87fd6
INFO:pytorch_pretrained_bert.tokenization_openai:loading merges file https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-merges.txt from cache at /media/xxxx/NewVolume/pre/0f8de0dbd6a2bb6bde7d758f4c120dd6dd20b46f2bf0a47bc899c89f46532fde.20808570f9a3169212a577f819c845330da870aeb14c40f7319819fce10c3b76
INFO:pytorch_pretrained_bert.modeling_openai:loading weights file https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-pytorch_model.bin from cache at /media/xxxx/NewVolume/pre/e45ee1afb14c5d77c946e66cb0fa70073a77882097a1a2cefd51fd24b172355e.e7ee3fcd07c695a4c9f31ca735502c090230d988de03202f7af9ebe1c3a4054c
INFO:pytorch_pretrained_bert.modeling_openai:loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-config.json from cache at /media/xxxx/NewVolume/pre/a27bb7c70e9002d7558d2682d5a95f3c0a8b31034616309459e0b51ef07ade09.f59b19eb0e361a0230a1106b66b8c6e7a994cb200cd63d9190cda8d56d75ff85
INFO:pytorch_pretrained_bert.modeling_openai:Model config {
  "afn": "gelu",
  "attn_pdrop": 0.1,
  "embd_pdrop": 0.1,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "n_ctx": 512,
  "n_embd": 768,
  "n_head": 12,
  "n_layer": 12,
  "n_positions": 512,
  "n_special": 0,
  "predict_special_tokens": true,
  "resid_pdrop": 0.1,
  "vocab_size": 40478
}

INFO:pytorch_pretrained_bert.tokenization_openai:Special tokens {'<bos>': 40478, '<eos>': 40479, '<paragraph>': 40480, '<answer-general>': 40481, '<answer-specific>': 40482, '<question-general>': 40483, '<question-specific>': 40484, '<pad>': 40485}
WARNING:pytorch_pretrained_bert.optimization:t_total value of -1 results in schedule not being applied
Traceback (most recent call last):
  File "question-generation/train.py", line 375, in <module>
    train()
  File "question-generation/train.py", line 279, in train
    model = DistributedDataParallel(model, device_ids=[args.local_rank], output_device=args.local_rank)
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 268, in __init__
    self.process_group = _get_default_group()
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 267, in _get_default_group
    raise RuntimeError("Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
Traceback (most recent call last):
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/xxxx/anaconda3/envs/squash/bin/python3', '-u', 'question-generation/train.py', '--local_rank=0', '--n_epochs', '1', '--output_dir', 'question-generation/gpt_question_generation']' returned non-zero exit status 1.
```

**Comment by martiansideofthemoon** [comment]
could you check if this line is being executed when you run your code?
https://github.com/martiansideofthemoon/squash-generation/blob/master/question-generation/train.py#L261

**Comment by aravindchaluvadi** [comment]
It is not getting executed 
**Below is the Trace Back**

>>>import torch
>>> torch.distributed.init_process_group(backend='nccl', init_method='env://')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 400, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/home/xxxx/anaconda3/envs/squash/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 119, in _env_rendezvous_handler
    raise _env_error("RANK")
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set

@martiansideofthemoon
