### ISSUE TITLE
Custom input is not working.

### ISSUE THREAD

**Issue by askaydevs** [martiansideofthemoon/squash-generation#33]
I was trying squash generation on custom input, however, while executing `./squash/pipeline_custom.sh` the following error occurred:

`Traceback (most recent call last):
  File "question-generation/interact.py", line 238, in <module>
    run()
  File "question-generation/interact.py", line 233, in run
    with open("squash/temp/%s/generated_questions.json" % args.key, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'squash/temp/None/generated_questions.json'`

Which led to the following errors in QA:

`Traceback (most recent call last):
  File "question-answering/run_squad.py", line 1100, in <module>
    main()
  File "question-answering/run_squad.py", line 1047, in main
    input_file=args.predict_file, is_training=False, version_2_with_negative=args.version_2_with_negative)
  File "question-answering/run_squad.py", line 124, in read_squad_examples
    with open(input_file, "r", encoding='utf-8') as reader:
FileNotFoundError: [Errno 2] No such file or directory: 'squash/temp/circ_001/generated_questions.json'
Combining Q and A ...
Traceback (most recent call last):
  File "squash/combine_qa.py", line 11, in <module>
    with open('squash/temp/%s/generated_questions.json' % args.key, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'squash/temp/circ_001/generated_questions.json'
Filtering bad Q/As ...
Traceback (most recent call last):
  File "squash/filter.py", line 190, in <module>
    with open('squash/temp/%s/final_qa_set.json' % args.key, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'squash/temp/circ_001/final_qa_set.json'`

Any ideas which might help?

**Comment by martiansideofthemoon** [comment]
It's missing the `--key` flag. Do you want to submit a PR to fix it?

**Comment by askaydevs** [comment]
I executed it with following:

`./squash/pipeline_custom.sh circ_001`

Where `circ_001` is a unique identifier.

**Comment by askaydevs** [comment]
I executed it with the following:

./squash/pipeline_custom.sh circ_001

Where circ_001 is a unique identifier that I am assuming is the key flag.

Not able to identify the root issue.

Any ideas for me to start with?
