### ISSUE TITLE
Custom input isn't working

### ISSUE THREAD

**Issue by askaydevs** [martiansideofthemoon/squash-generation#34]
I was trying squash generation on custom input, however, while executing `./squash/pipeline_custom.sh circ_001` the following error has occurred:

`Traceback (most recent call last):
  File "question-generation/interact.py", line 238, in <module>
    run()
  File "question-generation/interact.py", line 233, in run
    with open("squash/temp/%s/generated_questions.json" % args.key, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'squash/temp/None/generated_questions.json'
`

Here I am assuming `circ_001` is the key flag.

Any ideas which might help?

**Comment by martiansideofthemoon** [comment]
The code needs to be modified slightly, add the `--key $KEY` line to the interact command. Please submit a pull request if possible!
