### ISSUE TITLE
Issue while Running the squash website

### ISSUE THREAD

**Issue by ajinkya2903** [martiansideofthemoon/squash-generation#44]
Followed the Readme section of squash website, placed the pickle files properly in the respective folders and all scripts are running properly yet there is no output. How to solve this error? 
![output](https://user-images.githubusercontent.com/63385842/82569625-1fddf780-9b9e-11ea-919b-b2dc0a4dc1b7.png)

**Comment by ajinkya2903** [comment]
These are the outputs of my scripts. Please suggest some solution to proceed further.
![Screenshot_2020-05-22 Screenshot from 2020-05-22 15-14-12 png (PNG Image, 1366 × 768 pixels) - Scaled (83%)](https://user-images.githubusercontent.com/63385842/82687390-df9d7880-9c74-11ea-82a7-a711aa983862.png)
![Screenshot_2020-05-22 Screenshot from 2020-05-22 15-14-36 png (PNG Image, 1366 × 768 pixels) - Scaled (83%)](https://user-images.githubusercontent.com/63385842/82687396-e1ffd280-9c74-11ea-97de-bea0641032b1.png)
![Screenshot_2020-05-22 Screenshot from 2020-05-22 15-14-54 png (PNG Image, 1366 × 768 pixels) - Scaled (83%)](https://user-images.githubusercontent.com/63385842/82687397-e1ffd280-9c74-11ea-90c2-2f4354c4e5e1.png)
![Screenshot_2020-05-22 Screenshot from 2020-05-22 15-15-16 png (PNG Image, 1366 × 768 pixels) - Scaled (83%)](https://user-images.githubusercontent.com/63385842/82687407-e3c99600-9c74-11ea-8e69-7e43877ab3ec.png)
![Screenshot_2020-05-22 Screenshot from 2020-05-22 15-15-22 png (PNG Image, 1366 × 768 pixels) - Scaled (83%)](https://user-images.githubusercontent.com/63385842/82687409-e4622c80-9c74-11ea-8141-f49874b62c39.png)
![Screenshot_2020-05-22 Screenshot from 2020-05-22 15-15-29 png (PNG Image, 1366 × 768 pixels) - Scaled (83%)](https://user-images.githubusercontent.com/63385842/82687410-e4fac300-9c74-11ea-9b2a-85b5fbd25ba8.png)
![Screenshot_2020-05-22 Screenshot from 2020-05-22 15-15-36 png (PNG Image, 1366 × 768 pixels) - Scaled (83%)](https://user-images.githubusercontent.com/63385842/82687413-e5935980-9c74-11ea-80cb-789cc218c313.png)

**Comment by martiansideofthemoon** [comment]
Hi Ajinkya, thanks for the terminal logs they look great to me. Can you run an `ls` in the folder `squash-generation/squash` and `squash-generation/squash/generated_outputs`? Also, a `cat` on `squash-generation/squash/generated_outputs/queue/queue.txt` and `ls` on `squash-generation/squash/generated_outputs/inputs` will be helpful.

Overall this seems like an I/O issue, the backend code seems to be running.

**Comment by ajinkya2903** [comment]
Hey, @martiansideofthemoon thank you for your prompt reply. It worked for me. Thank you so much
