### ISSUE TITLE
Pretrained gpt2_corefs_question_generation

### ISSUE THREAD

**Issue by pmcrodrigues** [martiansideofthemoon/squash-generation#46]
While running pipeline_custom I get the error:
`name 'question-generation/gpt2_corefs_question_generation' was not found`
Is it absolutely necessary to train this model or can you provide the trained model?
And if it's necessary to train, how long does it take to train?

Thank you very much

**Comment by askaydevs** [comment]
Read the `README.md` file carefully, links to pre-trained models are provided by the author.

**Comment by martiansideofthemoon** [comment]
Thanks @askaydevs for helping out!
