### ISSUE TITLE
Demo website code link broken

### ISSUE THREAD

**Issue by pidugusundeep** [martiansideofthemoon/squash-generation#7]
Can you please fix the code link for the demo?

**Comment by martiansideofthemoon** [comment]
Hi, the demo is not up yet and the code is still a private repository. I am hoping to have the demo up by the end of the week.

**Comment by pidugusundeep** [comment]
@martiansideofthemoon thanks for the update.

**Comment by martiansideofthemoon** [comment]
Website code is now up! http://github.com/martiansideofthemoon/squash-website
